/* GENERATED by tools/lw-cards.mjs from Icon.card.jsx — edit the .jsx, run `npm run cards`. */
const { Icon, IconNames } = window.LeanWiseDesign_f2d907;
const names = IconNames || [];
function Sheet() {
  if (!names.length) return /* @__PURE__ */ React.createElement("div", { className: "cellx", style: { gridColumn: "1 / -1", color: "var(--lw-danger-on)" } }, /* @__PURE__ */ React.createElement("span", { className: "nm", style: { color: "inherit", fontSize: 11 } }, "IconNames is unavailable \u2014 _ds_bundle.js is stale or failed to load. Recompile."));
  return names.map((n) => /* @__PURE__ */ React.createElement("div", { className: "cellx", key: n }, /* @__PURE__ */ React.createElement(Icon, { name: n, size: 20 }), /* @__PURE__ */ React.createElement("span", { className: "nm" }, n)));
}
function Scale() {
  return [14, 16, 17, 19, 20].map((s) => /* @__PURE__ */ React.createElement("div", { className: "s", key: s }, /* @__PURE__ */ React.createElement(Icon, { name: "spark", size: s }), /* @__PURE__ */ React.createElement("span", null, s)));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Sheet, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Sheet, null));
ReactDOM.createRoot(document.getElementById("scale")).render(/* @__PURE__ */ React.createElement(Scale, null));
