/* GENERATED by tools/lw-cards.mjs from marketing.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Hero, FeatureGrid, StoryCard, LogoRail, Button, Stack, Grid } = LW;
const { Steps, Quote, Byline, ArticleCard } = LW;
const { Tabs, Pagination, EmptyState, Table } = LW;
ReactDOM.createRoot(document.getElementById("hero")).render(
  /* @__PURE__ */ React.createElement(
    Hero,
    {
      eyebrow: "Retrieval you can audit",
      title: /* @__PURE__ */ React.createElement(React.Fragment, null, "Answers your legal team can ", /* @__PURE__ */ React.createElement("em", null, "defend"), "."),
      lead: "LeanWise grounds every response in your own documents, and shows the passage it came from \u2014 so an answer is a starting point for review, not a claim you have to trust.",
      actions: /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Button, { variant: "cta", size: "lg" }, "Book a walkthrough"), /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "lg" }, "Read the spec")),
      aside: /* @__PURE__ */ React.createElement(Byline, { name: "A. Rossi", role: "Head of Legal Ops", date: "4 August 2026", dateTime: "2026-08-04" })
    }
  )
);
ReactDOM.createRoot(document.getElementById("root")).render(
  /* @__PURE__ */ React.createElement(Stack, { gap: 32, style: { paddingTop: 24 } }, /* @__PURE__ */ React.createElement(FeatureGrid, { features: [
    { title: "Grounded by default", body: "Every claim carries the passage it came from. No citation, no answer.", href: "#" },
    { title: "Hybrid retrieval", body: "Semantic and keyword search over one index, reranked before the model sees it.", href: "#" },
    { title: "Evaluated continuously", body: "Grounding and citation accuracy tracked per source, per release.", href: "#" }
  ] }), /* @__PURE__ */ React.createElement(Grid, { min: 280 }, /* @__PURE__ */ React.createElement(
    StoryCard,
    {
      title: "Northwind Legal",
      result: "61% faster contract review",
      body: "Cut first-pass review from 40 minutes to 15 across a 1,200-agreement portfolio."
    }
  ), /* @__PURE__ */ React.createElement(
    StoryCard,
    {
      title: "Kestrel Data",
      result: "Zero ungrounded answers",
      body: "Every response in the pilot cited a retrievable passage.",
      quote: "We stopped arguing about whether the model was right and started checking the page it pointed at.",
      person: "A. Rossi",
      role: "Head of Legal Ops"
    }
  )), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "logo rail \u2014 a card, not a real customer list"), /* @__PURE__ */ React.createElement(LogoRail, { logos: [{ name: "Northwind" }, { name: "Orbital" }, { name: "Kestrel" }, { name: "Vantage" }, { name: "Meridian" }] })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, 'logo rail \u2014 a mode="mono" raster beside the wordmark fallback'), /* @__PURE__ */ React.createElement(LogoRail, { logos: [{ name: "Northwind" }, { name: "LeanWise (mono raster)", src: "../../assets/logo-icon.png", mode: "mono" }, { name: "Vantage" }] })))
);
const steps = [
  { meta: "Phase 01", title: "Point it at a corpus", body: "One folder, one bucket or one connector. Nothing is copied out of your tenant." },
  { meta: "Phase 02", title: "Index and evaluate", body: "Hybrid retrieval over one index, then a grounding pass that scores what came back." },
  { meta: "Phase 03", title: "Answer with the passage attached", body: "No citation, no answer \u2014 the rule is enforced in the pipeline, not in review." }
];
ReactDOM.createRoot(document.getElementById("editorial")).render(
  /* @__PURE__ */ React.createElement(Stack, { gap: 32 }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "steps \u2014 vertical (a company timeline / how it works)"), /* @__PURE__ */ React.createElement(Steps, { items: steps })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "steps \u2014 horizontal, same markup, reverts to the stack under --lw-bp-md"), /* @__PURE__ */ React.createElement(Steps, { items: steps, orientation: "horizontal" })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "steps \u2014 horizontal, phase-name labels: the marker is a pill that grows and ellipsises"), /* @__PURE__ */ React.createElement(Steps, { orientation: "horizontal", items: [
    { label: "On the floor", title: "Years inside the supply base", body: "Working directly with suppliers, where quality, delivery and cost are the standing priorities." },
    { label: "Built against real paperwork", title: "The first checker", body: "One retailer's document set, one plant, one batch at a time." },
    { label: "In production", title: "Six plants", body: "Named on the customers page, with the status word beside each." },
    { label: "Q3", title: "What comes next", body: "Two products that are vision only, and say so." }
  ] })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "quote \u2014 the standalone pull quote; the spine is shared with StoryCard"), /* @__PURE__ */ React.createElement(Quote, { name: "A. Rossi", role: "Head of Legal Ops" }, "We stopped arguing about whether the model was right and started checking the page it pointed at.")), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "article head \u2014 .lw-eyebrow / .lw-h1 / .lw-lead / .lw-pill.lw-pill-link, plus .lw-byline"), /* @__PURE__ */ React.createElement("div", { className: "lw-article-head" }, /* @__PURE__ */ React.createElement("span", { className: "lw-eyebrow" }, "Engineering"), /* @__PURE__ */ React.createElement("h2", { className: "lw-h1" }, "What a grounded answer actually costs."), /* @__PURE__ */ React.createElement("p", { className: "lw-lead" }, "Every citation is a retrieval, a rerank and a second pass over the passage. Here is the budget, measured on our own fixtures."), /* @__PURE__ */ React.createElement("div", { className: "lw-cluster" }, /* @__PURE__ */ React.createElement("a", { className: "lw-pill lw-pill-link", href: "#" }, "Retrieval"), /* @__PURE__ */ React.createElement("a", { className: "lw-pill lw-pill-link", href: "#" }, "Evaluation"), /* @__PURE__ */ React.createElement("a", { className: "lw-pill lw-pill-link", href: "#" }, "Benchmarks")), /* @__PURE__ */ React.createElement(Byline, { name: "A. Rossi", role: "Head of Legal Ops", date: "4 August 2026", dateTime: "2026-08-04" }))), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "table \u2014 promoted to base.css in v1.7.0; a marketing page that argues from evidence has to show the evidence"), /* @__PURE__ */ React.createElement(
    Table,
    {
      caption: "Field-extraction accuracy by document type",
      columns: [
        { key: "type", header: "Document type" },
        { key: "score", header: "Accuracy", num: true },
        { key: "n", header: "Samples", num: true }
      ],
      rows: [
        { type: "Test Report", score: "96.5%", n: "292" },
        { type: "Self Declaration", score: "86.1%", n: "20" },
        { type: "Bill of Materials", score: "100.0%", n: "2" }
      ]
    }
  )), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "article index chrome \u2014 Tabs, Pagination and EmptyState, all promoted to base.css in v1.3.1"), /* @__PURE__ */ React.createElement(Stack, { gap: 20 }, /* @__PURE__ */ React.createElement(Tabs, { label: "Article categories", tabs: [{ value: "all", label: "All", count: 24 }, { value: "eng", label: "Engineering", count: 11 }, { value: "prod", label: "Product", count: 9 }, { value: "none", label: "Archive", count: 0 }], value: "none" }), /* @__PURE__ */ React.createElement(
    EmptyState,
    {
      icon: "inbox",
      title: "No articles in Archive",
      description: "Nothing has been archived yet. Published posts stay in All until you move them.",
      action: /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "sm" }, "Back to all")
    }
  ), /* @__PURE__ */ React.createElement(Pagination, { page: 2, pageSize: 10, total: 24, onPageChange: () => {
  } }))), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "article index \u2014 Grid of ArticleCard; no .lw-post class exists or is needed"), /* @__PURE__ */ React.createElement(Grid, { min: 280 }, /* @__PURE__ */ React.createElement(
    ArticleCard,
    {
      href: "#",
      category: "Engineering",
      title: "What a grounded answer actually costs",
      dek: "The retrieval, the rerank and the second pass, measured on our own fixtures.",
      tags: ["Retrieval", "Benchmarks"],
      author: "A. Rossi",
      role: "Head of Legal Ops",
      date: "4 Aug 2026",
      dateTime: "2026-08-04",
      readTime: "7 min read"
    }
  ), /* @__PURE__ */ React.createElement(
    ArticleCard,
    {
      href: "#",
      category: "Product",
      title: "Why every answer carries its passage",
      dek: "No citation, no answer \u2014 enforced in the pipeline rather than in review.",
      tags: ["Grounding"],
      author: "M. Chen",
      role: "Engineering",
      date: "21 Jul 2026",
      dateTime: "2026-07-21",
      readTime: "4 min read"
    }
  ))))
);
