/* GENERATED by tools/lw-cards.mjs from pricing.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { PlanCard, CompareTable, Grid, Segmented, Eyebrow } = LW;
const core = [
  { label: "Grounded answers with the source passage attached" },
  { label: "Document ingest \u2014 PDF, DOCX, XLSX" },
  { label: "Retrieval evaluation on your own fixtures" }
];
ReactDOM.createRoot(document.getElementById("plans")).render(
  /* @__PURE__ */ React.createElement(Grid, { min: 260 }, /* @__PURE__ */ React.createElement(
    PlanCard,
    {
      name: "Pilot",
      tagline: "one team, one corpus",
      desc: "Everything needed to decide whether the answers hold up on your own documents.",
      features: [...core, { label: "SSO / SAML", included: false }, { label: "Dedicated tenancy", included: false }],
      cta: { label: "Start a pilot", href: "#" }
    }
  ), /* @__PURE__ */ React.createElement(
    PlanCard,
    {
      featured: true,
      ribbon: "Most chosen",
      name: "Team",
      price: "$390",
      unit: "USD",
      period: "/ month",
      desc: "For a department running review as part of its normal week.",
      features: [...core, { label: "SSO / SAML" }, { label: "Dedicated tenancy", included: false }],
      cta: { label: "Book a walkthrough", href: "#" }
    }
  ), /* @__PURE__ */ React.createElement(
    PlanCard,
    {
      name: "Enterprise",
      tagline: "scoped per deployment",
      desc: "Priced against the corpus, the residency requirement and the review volume \u2014 so there is no list price to print, and none is printed.",
      features: [...core, { label: "SSO / SAML" }, { label: "Dedicated tenancy" }],
      cta: { label: "Talk to us", href: "#" }
    }
  ), /* @__PURE__ */ React.createElement(
    PlanCard,
    {
      "data-band": "dark",
      name: "Enterprise",
      tagline: "the same card, one attribute",
      desc: 'data-band="dark" \u2014 not one child carries a dark variant.',
      features: [...core, { label: "SSO / SAML" }, { label: "Dedicated tenancy" }],
      cta: { label: "Talk to us", href: "#" }
    }
  ))
);
function PlansHead() {
  const [period, setPeriod] = React.useState("annual");
  return /* @__PURE__ */ React.createElement("div", { className: "lw-plans-head" }, /* @__PURE__ */ React.createElement(Eyebrow, null, "Billing period"), /* @__PURE__ */ React.createElement(
    Segmented,
    {
      label: "Billing period",
      options: [{ value: "monthly", label: "Monthly" }, { value: "annual", label: "Annual" }],
      value: period,
      onChange: setPeriod
    }
  ), /* @__PURE__ */ React.createElement("span", { className: "lw-pill" }, "2 months free on annual"));
}
ReactDOM.createRoot(document.getElementById("plans-head")).render(/* @__PURE__ */ React.createElement(PlansHead, null));
ReactDOM.createRoot(document.getElementById("compare")).render(
  /* @__PURE__ */ React.createElement(
    CompareTable,
    {
      caption: "What each plan includes. Sticky on both axes; the matrix scrolls, the page does not.",
      columns: [
        { key: "pilot", label: "Pilot" },
        { key: "team", label: "Team", featured: true },
        { key: "ent", label: "Enterprise" }
      ],
      groups: [
        { label: "Retrieval", rows: [
          { label: "Grounded answers with source passages", values: [true, true, true] },
          { label: "Retrieval evaluation on your fixtures", values: [true, true, true] },
          { label: "Corpus size", values: ["10k pages", "250k pages", "scoped"] }
        ] },
        { label: "Access", rows: [
          { label: "SSO / SAML", values: [false, true, true] },
          { label: "Dedicated tenancy", values: [false, false, true] },
          { label: "Data residency", values: [false, false, "on request"] }
        ] },
        { label: "Support", rows: [
          { label: "Named reviewer", values: [false, true, true] },
          { label: "Response target", values: ["2 business days", "1 business day", "scoped"] }
        ] }
      ]
    }
  )
);
