/* GENERATED by tools/lw-cards.mjs from site-chrome.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { TopBar, SiteFooter, Button, Icon, Cluster } = LW;
const Announce = ({ onDismiss, children }) => /* @__PURE__ */ React.createElement("div", { className: "lw-announce", role: "status" }, children, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Dismiss announcement", onClick: onDismiss }, /* @__PURE__ */ React.createElement(Icon, { name: "close", size: 14 })));
const navLinks = [
  { href: "#", label: "Product" },
  { href: "#", label: "Customers" },
  { href: "#", label: "Resources", current: true },
  { href: "#", label: "Pricing" }
];
const columns = [
  { heading: "Product", links: [
    { href: "#", label: "Overview" },
    { href: "#", label: "Retrieval" },
    { href: "#", label: "Evaluation" },
    { label: "SOC 2 \u2014 in progress" }
  ] },
  { heading: "Resources", links: [
    { href: "#", label: "Resources", current: true },
    { href: "#", label: "Docs", external: true },
    { href: "#", label: "Changelog" }
  ] },
  { heading: "Company", links: [
    { href: "#", label: "About" },
    { href: "#", label: "Careers" },
    { href: "#", label: "Contact" }
  ] }
];
const social = /* @__PURE__ */ React.createElement(Cluster, null, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Email us" }, /* @__PURE__ */ React.createElement(Icon, { name: "mail", size: 16 })), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Source repository" }, /* @__PURE__ */ React.createElement(Icon, { name: "code", size: 16 })), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Status page" }, /* @__PURE__ */ React.createElement(Icon, { name: "link", size: 16 })));
const legal = "LeanWise AI is a retrieval and review tool. It does not provide legal advice, and an answer it grounds in your documents is a starting point for review rather than a determination.";
ReactDOM.createRoot(document.getElementById("chrome")).render(
  /* @__PURE__ */ React.createElement("div", { style: { border: "1px solid var(--lw-line)", borderRadius: "var(--lw-radius-lg)", overflow: "hidden" } }, /* @__PURE__ */ React.createElement(Announce, { onDismiss: () => {
  } }, "Retrieval evaluation is now on by default. ", /* @__PURE__ */ React.createElement("a", { href: "#" }, "Read the note")), /* @__PURE__ */ React.createElement(TopBar, { brand: "LeanWise AI", brandHref: "#", logo: true, links: navLinks, className: "nav-center" }, /* @__PURE__ */ React.createElement(Button, { variant: "brand", size: "sm" }, "Book a walkthrough")), /* @__PURE__ */ React.createElement("div", { style: { padding: "28px 20px", color: "var(--lw-fg-subtle)", fontSize: 13 } }, "The header sits 36px down, not at zero. Scroll a real page and the strip stays; the header stays under it."))
);
ReactDOM.createRoot(document.getElementById("footer-light")).render(
  /* @__PURE__ */ React.createElement(
    SiteFooter,
    {
      brand: /* @__PURE__ */ React.createElement("b", null, "LeanWise AI"),
      desc: "Answers grounded in your own documents, with the passage they came from attached.",
      columns,
      legal,
      bottom: /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("span", null, "\xA9 LeanWise AI"), social)
    }
  )
);
ReactDOM.createRoot(document.getElementById("footer-dark")).render(
  /* @__PURE__ */ React.createElement(
    SiteFooter,
    {
      dark: true,
      brand: /* @__PURE__ */ React.createElement("b", null, "LeanWise AI"),
      desc: "The same markup, one attribute different. No child carries a dark variant.",
      columns,
      legal,
      bottom: /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("span", null, "\xA9 LeanWise AI"), social)
    }
  )
);
