/* GENERATED by tools/lw-cards.mjs from ai.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Button, Icon, Stack } = LW;
function Act({ icon, label, title }) {
  return /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": label, title: title || label }, /* @__PURE__ */ React.createElement(Icon, { name: icon, size: 17 }));
}
function Msg({ role, who, streaming, children }) {
  return /* @__PURE__ */ React.createElement("div", { className: "lw-msg " + role, "data-streaming": streaming ? "true" : void 0 }, /* @__PURE__ */ React.createElement("span", { className: "lw-msg-avatar", "aria-hidden": "true" }, /* @__PURE__ */ React.createElement(Icon, { name: role === "ai" ? "spark" : "user", size: role === "ai" ? 19 : 16 })), /* @__PURE__ */ React.createElement("div", { className: "lw-msg-main" }, /* @__PURE__ */ React.createElement("span", { className: "who" }, who), /* @__PURE__ */ React.createElement("div", { className: "body" }, children)));
}
const Cite = ({ n }) => /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-source", "aria-label": "Source " + n }, n);
function Demo() {
  return /* @__PURE__ */ React.createElement(Stack, { gap: 16 }, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "conversation"), /* @__PURE__ */ React.createElement("div", { className: "thread" }, /* @__PURE__ */ React.createElement(Msg, { role: "user", who: "You" }, "Which contracts auto-renew before the end of Q3?", /* @__PURE__ */ React.createElement("div", { className: "lw-msg-actions" }, /* @__PURE__ */ React.createElement(Act, { icon: "edit", label: "Edit question", title: "Edit" }))), /* @__PURE__ */ React.createElement(Msg, { role: "ai", who: "LeanWise", streaming: true }, /* @__PURE__ */ React.createElement("p", { style: { margin: 0 } }, "Four agreements auto-renew before 30 September."), /* @__PURE__ */ React.createElement("p", { style: { margin: ".7em 0 0" } }, "The ", /* @__PURE__ */ React.createElement("b", null, "master services agreement"), " renews on 12 August with a 60-day notice window, so the decision date has already passed ", /* @__PURE__ */ React.createElement(Cite, { n: 1 }), ". ", /* @__PURE__ */ React.createElement("b", null, "Statement of work 3"), " and the ", /* @__PURE__ */ React.createElement("b", null, "amended agreement"), " both renew on 1 September ", /* @__PURE__ */ React.createElement(Cite, { n: 2 }), /* @__PURE__ */ React.createElement(Cite, { n: 3 }), ", and the", /* @__PURE__ */ React.createElement("b", null, " framework agreement"), " renews on 22 September under an evergreen clause ", /* @__PURE__ */ React.createElement(Cite, { n: 4 }), "."), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginTop: 14 } }, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "lw-icon-btn",
      "aria-label": "Show the 4 cited passages",
      title: "4 citations",
      style: { width: "auto", gap: 7, height: 28, padding: "0 4px", color: "var(--lw-fg-muted)", fontFamily: "var(--lw-font-mono)", fontSize: 11, letterSpacing: ".04em" }
    },
    /* @__PURE__ */ React.createElement(Icon, { name: "list", size: 18 }),
    "4"
  ), /* @__PURE__ */ React.createElement("span", { style: { flex: 1 } }), /* @__PURE__ */ React.createElement("div", { className: "lw-msg-actions" }, /* @__PURE__ */ React.createElement(Act, { icon: "copy", label: "Copy answer", title: "Copy" }), /* @__PURE__ */ React.createElement(Act, { icon: "retry", label: "Regenerate answer", title: "Retry" }), /* @__PURE__ */ React.createElement(Act, { icon: "download", label: "Export answer", title: "Export" }))))), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "provenance panel"), /* @__PURE__ */ React.createElement(
    "span",
    {
      className: "lw-confidence",
      style: { "--lw-confidence": "91%" },
      role: "meter",
      "aria-valuenow": 91,
      "aria-valuemin": 0,
      "aria-valuemax": 100,
      "aria-label": "match"
    },
    /* @__PURE__ */ React.createElement("span", { className: "rail", "aria-hidden": "true" }, /* @__PURE__ */ React.createElement("i", null)),
    /* @__PURE__ */ React.createElement("span", null, "91%")
  ), /* @__PURE__ */ React.createElement("ol", { className: "lw-trace" }, /* @__PURE__ */ React.createElement("li", { "data-state": "done" }, /* @__PURE__ */ React.createElement("span", { className: "step" }, "Parsed the question"), /* @__PURE__ */ React.createElement("span", { className: "meta" }, "intent: date-filter \xB7 entity: contract")), /* @__PURE__ */ React.createElement("li", { "data-state": "done" }, /* @__PURE__ */ React.createElement("span", { className: "step" }, "Retrieved 41 candidate passages"), /* @__PURE__ */ React.createElement("span", { className: "meta" }, "hybrid \xB7 240ms")), /* @__PURE__ */ React.createElement("li", { "data-state": "active" }, /* @__PURE__ */ React.createElement("span", { className: "step" }, "Reranking and grounding"), /* @__PURE__ */ React.createElement("span", { className: "meta" }, "cross-encoder")), /* @__PURE__ */ React.createElement("li", { "data-state": "pending" }, /* @__PURE__ */ React.createElement("span", { className: "step" }, "Compose answer"))), /* @__PURE__ */ React.createElement("div", { className: "lw-source-list" }, [
    { n: 1, t: "Northwind \u2014 Master Services Agreement", m: "contracts/2024 \xB7 p.14 \xB7 94% match" },
    { n: 2, t: "Orbital Systems \u2014 Statement of Work 3", m: "contracts/2024 \xB7 p.2 \xB7 88% match" },
    { n: 3, t: "Kestrel Data \u2014 MSA (amended)", m: "contracts/2023 \xB7 p.31 \xB7 81% match" }
  ].map((s) => /* @__PURE__ */ React.createElement("button", { key: s.n, type: "button", className: "lw-source-item" }, /* @__PURE__ */ React.createElement("span", { className: "n" }, s.n), /* @__PURE__ */ React.createElement("span", { className: "lw-source-main" }, /* @__PURE__ */ React.createElement("span", { className: "t" }, s.t), /* @__PURE__ */ React.createElement("span", { className: "m" }, s.m))))), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "prompt"), /* @__PURE__ */ React.createElement("div", { className: "thread" }, /* @__PURE__ */ React.createElement("div", { className: "lw-prompt" }, /* @__PURE__ */ React.createElement(
    "textarea",
    {
      rows: 2,
      "aria-label": "Prompt",
      defaultValue: "",
      placeholder: "Ask anything about your documents\u2026"
    }
  ), /* @__PURE__ */ React.createElement("div", { className: "lw-prompt-foot" }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, width: "100%" } }, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Attach a document", title: "Attach a document" }, /* @__PURE__ */ React.createElement(Icon, { name: "paperclip", size: 19 })), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Choose which sources to search", title: "All sources" }, /* @__PURE__ */ React.createElement(Icon, { name: "layers", size: 19 })), /* @__PURE__ */ React.createElement("span", { style: { flex: 1 } }), /* @__PURE__ */ React.createElement("span", { className: "lw-prompt-hint" }, "\u21E7\u21B5 for newline"), /* @__PURE__ */ React.createElement(Button, { size: "sm", iconOnly: true, "aria-label": "Send", title: "Send" }, /* @__PURE__ */ React.createElement(Icon, { name: "send", size: 16 }))))), /* @__PURE__ */ React.createElement("p", { style: { margin: "8px 0 0", textAlign: "center", fontSize: 11.5, color: "var(--lw-fg-subtle)", textWrap: "pretty" } }, "AI can make mistakes. Please double-check responses.")));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
