/* GENERATED by tools/lw-cards.mjs from ai.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { PromptInput, Message, SourceChip, SourceList, ConfidenceMeter, AgentTrace, Button, Icon, Stack, Cluster, Chip } = LW;
function Act({ icon, label, title }) {
  return /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": label, title: title || label }, /* @__PURE__ */ React.createElement(Icon, { name: icon, size: 17 }));
}
function Demo({ ns }) {
  const [q, setQ] = React.useState("");
  return /* @__PURE__ */ React.createElement(Stack, { gap: 16 }, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "conversation"), /* @__PURE__ */ React.createElement("div", { className: "thread" }, /* @__PURE__ */ React.createElement(Message, { role: "user", who: "You" }, "Which contracts auto-renew before the end of Q3?", /* @__PURE__ */ React.createElement("div", { className: "lw-msg-actions" }, /* @__PURE__ */ React.createElement(Act, { icon: "edit", label: "Edit question", title: "Edit" }))), /* @__PURE__ */ React.createElement(Message, { role: "ai", streaming: true }, /* @__PURE__ */ React.createElement("p", { style: { margin: 0 } }, "Four agreements auto-renew before 30 September."), /* @__PURE__ */ React.createElement("p", { style: { margin: ".7em 0 0" } }, "The ", /* @__PURE__ */ React.createElement("b", null, "master services agreement"), " renews on 12 August with a 60-day notice window, so the decision date has already passed ", /* @__PURE__ */ React.createElement(SourceChip, { n: 1 }), ". ", /* @__PURE__ */ React.createElement("b", null, "Statement of work 3"), " and the ", /* @__PURE__ */ React.createElement("b", null, "amended agreement"), " both renew on 1 September ", /* @__PURE__ */ React.createElement(SourceChip, { n: 2 }), /* @__PURE__ */ React.createElement(SourceChip, { n: 3 }), ", and the", /* @__PURE__ */ React.createElement("b", null, " framework agreement"), " renews on 22 September under an evergreen clause ", /* @__PURE__ */ React.createElement(SourceChip, { n: 4 }), "."), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginTop: 14 } }, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "lw-icon-btn",
      "aria-label": "Show the 4 cited passages",
      title: "4 citations",
      style: { width: "auto", gap: 7, height: 28, padding: "0 4px", color: "var(--lw-fg-muted)", fontFamily: "var(--lw-font-mono)", fontSize: 11, letterSpacing: ".04em" }
    },
    /* @__PURE__ */ React.createElement(Icon, { name: "list", size: 18 }),
    "4"
  ), /* @__PURE__ */ React.createElement("span", { style: { flex: 1 } }), /* @__PURE__ */ React.createElement("div", { className: "lw-msg-actions" }, /* @__PURE__ */ React.createElement(Act, { icon: "copy", label: "Copy answer", title: "Copy" }), /* @__PURE__ */ React.createElement(Act, { icon: "retry", label: "Regenerate answer", title: "Retry" }), /* @__PURE__ */ React.createElement(Act, { icon: "download", label: "Export answer", title: "Export" }))))), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "provenance panel"), /* @__PURE__ */ React.createElement(ConfidenceMeter, { value: 91 }), /* @__PURE__ */ React.createElement(AgentTrace, { steps: [
    { label: "Parsed the question", meta: "intent: date-filter \xB7 entity: contract", state: "done" },
    { label: "Retrieved 41 candidate passages", meta: "hybrid \xB7 240ms", state: "done" },
    { label: "Reranking and grounding", meta: "cross-encoder", state: "active" },
    { label: "Compose answer", state: "pending" }
  ] }), /* @__PURE__ */ React.createElement(SourceList, { sources: [
    { n: 1, title: "Northwind \u2014 Master Services Agreement", meta: "contracts/2024 \xB7 p.14 \xB7 94% match" },
    { n: 2, title: "Orbital Systems \u2014 Statement of Work 3", meta: "contracts/2024 \xB7 p.2 \xB7 88% match" },
    { n: 3, title: "Kestrel Data \u2014 MSA (amended)", meta: "contracts/2023 \xB7 p.31 \xB7 81% match" }
  ] }), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "prompt"), /* @__PURE__ */ React.createElement("div", { className: "thread" }, /* @__PURE__ */ React.createElement(PromptInput, { value: q, onChange: setQ }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, width: "100%" } }, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Attach a document", title: "Attach a document" }, /* @__PURE__ */ React.createElement(Icon, { name: "paperclip", size: 19 })), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Choose which sources to search", title: "All sources" }, /* @__PURE__ */ React.createElement(Icon, { name: "layers", size: 19 })), /* @__PURE__ */ React.createElement("span", { style: { flex: 1 } }), /* @__PURE__ */ React.createElement("span", { className: "lw-prompt-hint" }, "\u21E7\u21B5 for newline"), /* @__PURE__ */ React.createElement(Button, { size: "sm", iconOnly: true, "aria-label": "Send", title: "Send" }, /* @__PURE__ */ React.createElement(Icon, { name: "send", size: 16 })))), /* @__PURE__ */ React.createElement("p", { style: { margin: "8px 0 0", textAlign: "center", fontSize: 11.5, color: "var(--lw-fg-subtle)", textWrap: "pretty" } }, "AI can make mistakes. Please double-check responses.")));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, { ns: "l" }));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, { ns: "d" }));
