/* Builds theme.css — the whole LeanWise theme for a Tailwind v4 + shadcn/ui app —
   from src/palette.mjs. Also the one place the non-colour scales live. */
import { ramp, themes } from "../../src/palette.mjs";

export const FONTS = {
  sans: '"Geist", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
  mono: '"Geist Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
};

/* App type scale: size / line-height. 14 is app body, 12 the floor. */
export const TYPE = {
  xs: ["0.75rem", "1rem"],
  sm: ["0.875rem", "1.25rem"],
  base: ["1rem", "1.5rem"],
  lg: ["1.125rem", "1.75rem"],
  xl: ["1.25rem", "1.75rem"],
  "2xl": ["1.5rem", "2rem"],
  "3xl": ["1.875rem", "2.25rem"],
  /* Marketing display — fluid. */
  "display-sm": ["clamp(1.75rem, 3.4vw, 3rem)", "1.1"],
  display: ["clamp(2.375rem, 5vw, 4.5rem)", "1.05"],
};

export const RADIUS = "0.625rem";

const decl = (obj, indent = "  ") =>
  Object.entries(obj).map(([k, v]) => `${indent}--${k}: ${v};`).join("\n");

/* Every palette role, plus the ramp, becomes a Tailwind colour utility. */
const colorNames = Object.keys(themes.light);

export function buildThemeCss() {
  const rampVars = Object.fromEntries(Object.entries(ramp).map(([k, v]) => [`brand-${k}`, v]));
  const themeInline = {
    ...Object.fromEntries(colorNames.map((n) => [`color-${n}`, `var(--${n})`])),
    ...Object.fromEntries(Object.keys(ramp).map((k) => [`color-brand-${k}`, `var(--brand-${k})`])),
    "color-brand": "var(--brand-600)",
    "font-sans": "var(--font-sans)",
    "font-mono": "var(--font-mono)",
    "radius-sm": "calc(var(--radius) * 0.6)",
    "radius-md": "calc(var(--radius) * 0.8)",
    "radius-lg": "var(--radius)",
    "radius-xl": "calc(var(--radius) * 1.4)",
    ...Object.fromEntries(
      Object.entries(TYPE).flatMap(([k, [size, lh]]) => [
        [`text-${k}`, size],
        [`text-${k}--line-height`, lh],
      ]),
    ),
  };

  return `/* GENERATED by \`npm run gen\` from src/palette.mjs — do not edit.
   LeanWise theme for Tailwind v4 + shadcn/ui. Import once, after tailwindcss:
     @import "tailwindcss";
     @import "@leanwise/design/theme.css";                                  */

@custom-variant dark (&:is(.dark *));

:root {
  --radius: ${RADIUS};
  --font-sans: ${FONTS.sans};
  --font-mono: ${FONTS.mono};
${decl(rampVars)}
${decl(themes.light)}
}

.dark {
  color-scheme: dark;
${decl(themes.dark)}
}

@theme inline {
${decl(themeInline)}
}

@layer base {
  * {
    @apply border-border outline-ring;
  }
  body {
    @apply bg-background text-foreground font-sans;
    font-size: var(--text-sm);
    line-height: var(--text-sm--line-height);
    -webkit-font-smoothing: antialiased;
  }
  /* Every interactive element shows the pointer — shadcn's Button no longer does. */
  button:not(:disabled),
  [role="button"]:not([aria-disabled="true"]),
  [role="tab"], [role="menuitem"], [role="menuitemcheckbox"], [role="menuitemradio"],
  [role="option"], [role="switch"], [role="checkbox"], [role="radio"],
  a[href], summary, select, label[for], input[type="checkbox"], input[type="radio"] {
    cursor: pointer;
  }
}

/* Focus is a SOLID brand ring, never faded. Deliberately UNLAYERED: an unlayered
   rule beats every @layer rule, so it wins over the \`ring-ring/50\` utilities stock
   shadcn components carry — no component has to be forked to get it. */
:focus-visible {
  outline: 2px solid var(--ring);
  outline-offset: 2px;
}
[data-slot]:focus-visible {
  outline: none;
  --tw-ring-color: var(--ring);
  box-shadow: 0 0 0 2px var(--background), 0 0 0 4px var(--ring);
}
:is(input, textarea, select, [data-slot="input"], [data-slot="textarea"],
    [data-slot="select-trigger"], [data-slot="input-group"]):focus-visible {
  outline: none;
  border-color: var(--ring);
  box-shadow: 0 0 0 1px var(--ring);
}
`;
}
