/* tokens.json — the palette and scales as DTCG, resolved to hex, for tools that
   cannot read CSS (Figma, Style Dictionary, native apps). */
import { ANCHORS, ramp, themes } from "../../src/palette.mjs";
import { FONTS, TYPE, RADIUS } from "./theme.mjs";
import { toHex } from "./parse.mjs";

const color = (v) => ({ $type: "color", $value: toHex(v) });
const group = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, color(v)]));

export function buildTokensJson() {
  const doc = {
    $description: "GENERATED by `npm run gen` from src/palette.mjs — do not edit.",
    anchor: group(ANCHORS),
    brand: group(ramp),
    light: group(themes.light),
    dark: group(themes.dark),
    font: Object.fromEntries(Object.entries(FONTS).map(([k, v]) => [k, { $type: "fontFamily", $value: v }])),
    text: Object.fromEntries(Object.entries(TYPE).map(([k, [size, lh]]) =>
      [k, { $type: "dimension", $value: size, $extensions: { lineHeight: lh } }])),
    radius: { $type: "dimension", $value: RADIUS },
  };
  return JSON.stringify(doc, null, 2) + "\n";
}
