/* GENERATED by tools/lw-cards.mjs from Dialog-open.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Dialog, OverlayProvider, Button, Field, Input } = LW;
function Demo() {
  const [open, setOpen] = React.useState(true);
  React.useEffect(() => {
    if (!open) setOpen(true);
  }, [open]);
  return /* @__PURE__ */ React.createElement(OverlayProvider, null, /* @__PURE__ */ React.createElement("p", { className: "lbl-eyebrow" }, "dialog, open"), /* @__PURE__ */ React.createElement(
    Dialog,
    {
      open,
      onClose: () => setOpen(false),
      title: "Re-index this source?",
      description: "41,208 chunks will be re-embedded. Queries keep serving the current index until the new one passes evaluation.",
      footer: /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Button, { variant: "ghost", onClick: () => setOpen(false) }, "Cancel"), /* @__PURE__ */ React.createElement(Button, { onClick: () => setOpen(false) }, "Re-index"))
    },
    /* @__PURE__ */ React.createElement("div", { style: { marginTop: 14 } }, /* @__PURE__ */ React.createElement(Field, { label: "Confirm the source name", htmlFor: "cf" }, /* @__PURE__ */ React.createElement(Input, { id: "cf", placeholder: "contracts/2024" })))
  ));
}
ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(Demo, null));
