/* GENERATED by tools/lw-cards.mjs from Menu.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Popover, Menu, Button, Stack, Cluster, Field, Input, Switch } = LW;
const items = [
  { type: "label", label: "This source" },
  { value: "open", label: "Open in workbench", icon: "external", kbd: "\u2318O" },
  { value: "reindex", label: "Re-index", icon: "retry" },
  { value: "export", label: "Export chunks", icon: "download", kbd: "\u2318E" },
  { type: "separator" },
  { value: "pin", label: "Pin to sidebar", icon: "pin", checked: true },
  { value: "watch", label: "Watch for changes", icon: "eye", checked: false },
  { type: "separator" },
  { value: "delete", label: "Delete source", icon: "trash", danger: true }
];
function Demo() {
  const [last, setLast] = React.useState(null);
  return /* @__PURE__ */ React.createElement(Stack, { gap: 14 }, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "menu \u2014 arrows, Home/End, typeahead, Esc"), /* @__PURE__ */ React.createElement(Cluster, null, /* @__PURE__ */ React.createElement(
    Menu,
    {
      items,
      label: "Source actions",
      onSelect: (v) => setLast(v),
      trigger: /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "sm" }, "Actions")
    }
  ), /* @__PURE__ */ React.createElement(
    Menu,
    {
      items,
      label: "Source actions",
      placement: "bottom-end",
      onSelect: (v) => setLast(v),
      trigger: /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "sm", iconOnly: true, "aria-label": "More" }, /* @__PURE__ */ React.createElement("span", { className: "lw-icon" }, "\u22EE"))
    }
  ), /* @__PURE__ */ React.createElement(
    Menu,
    {
      items,
      label: "Source actions",
      placement: "top-start",
      onSelect: (v) => setLast(v),
      trigger: /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "sm" }, "Above (flips if it will not fit)")
    }
  )), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "popover \u2014 arbitrary content, ", last ? "last chose: " + last : "nothing chosen yet"), /* @__PURE__ */ React.createElement(Cluster, null, /* @__PURE__ */ React.createElement(
    Popover,
    {
      padded: true,
      label: "Filter results",
      placement: "bottom-start",
      trigger: /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "sm" }, "Filters")
    },
    /* @__PURE__ */ React.createElement(Stack, { gap: 12 }, /* @__PURE__ */ React.createElement(Field, { label: "Minimum score", htmlFor: "ms" }, /* @__PURE__ */ React.createElement(Input, { id: "ms", placeholder: "0.72" })), /* @__PURE__ */ React.createElement(Switch, { label: "Only grounded answers", defaultChecked: true }))
  )));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
