/* GENERATED by tools/lw-cards.mjs from overlays.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Dialog, Drawer, Toast, ToastRegion, Tooltip, Button, Stack, Cluster, Field, Input } = LW;
function Demo() {
  const [open, setOpen] = React.useState(false);
  const [drawer, setDrawer] = React.useState(false);
  return /* @__PURE__ */ React.createElement(Stack, { gap: 14 }, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "dialog"), /* @__PURE__ */ React.createElement(Cluster, null, /* @__PURE__ */ React.createElement(Button, { onClick: () => setOpen(true) }, "Open dialog"), /* @__PURE__ */ React.createElement(Button, { variant: "ghost", onClick: () => setDrawer(true) }, "Open drawer"), /* @__PURE__ */ React.createElement(Tooltip, { tip: "Hints only \u2014 never content the user needs" }, /* @__PURE__ */ React.createElement(Button, { variant: "ghost", size: "sm" }, "Hover me"))), /* @__PURE__ */ React.createElement(
    Dialog,
    {
      open,
      onClose: () => setOpen(false),
      title: "Re-index this source?",
      description: "41,208 chunks will be re-embedded. Queries keep serving the current index until the new one passes evaluation.",
      footer: /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Button, { variant: "ghost", onClick: () => setOpen(false) }, "Cancel"), /* @__PURE__ */ React.createElement(Button, { onClick: () => setOpen(false) }, "Re-index"))
    },
    /* @__PURE__ */ React.createElement("div", { style: { marginTop: 14 } }, /* @__PURE__ */ React.createElement(Field, { label: "Confirm the source name", htmlFor: "cf" }, /* @__PURE__ */ React.createElement(Input, { id: "cf", placeholder: "contracts/2024" })))
  ), /* @__PURE__ */ React.createElement(
    Drawer,
    {
      open: drawer,
      onClose: () => setDrawer(false),
      title: "contracts/2024",
      description: "Last indexed 4 hours ago. 41,208 chunks across 1,284 documents.",
      footer: /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Button, { variant: "ghost", onClick: () => setDrawer(false) }, "Close"), /* @__PURE__ */ React.createElement(Button, { onClick: () => setDrawer(false) }, "Re-index"))
    },
    /* @__PURE__ */ React.createElement("div", { style: { marginTop: 14 } }, /* @__PURE__ */ React.createElement(Field, { label: "Rename source", htmlFor: "rn" }, /* @__PURE__ */ React.createElement(Input, { id: "rn", defaultValue: "contracts/2024" })))
  ), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow" }, "toasts \u2014 status is a word, not only a colour"), /* @__PURE__ */ React.createElement(Stack, { gap: 8 }, /* @__PURE__ */ React.createElement(Toast, { tone: "success" }, "Index rebuilt. 1,284 documents, 41,208 chunks."), /* @__PURE__ */ React.createElement(Toast, { tone: "warning" }, "3 documents skipped \u2014 unsupported encoding."), /* @__PURE__ */ React.createElement(Toast, { tone: "danger" }, "Embedding failed after 2 retries.")));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
