#!/usr/bin/env node
/**
 * The card compiler — `<name>.card.jsx` (source) → `<name>.card.js` (generated).
 *
 * Run: node tools/lw-cards.mjs          (compiles; also migrates any inline block)
 *      node tools/lw-cards.mjs --check  (fails when a .card.js is missing or stale,
 *                                        or a card still carries an inline block)
 *
 * Until v1.13.0 every React specimen card inlined its JSX in a
 * `<script type="text/babel">` block and loaded `preview/_vendor/babel.min.js`
 * — 3.1 MB of compiler, parsed and run by the browser on every card open, and
 * committed to the repo for the privilege. Two browser gates open 27 such cards
 * across four grounds each; that is 3.1 MB × 108 page loads of transpiler per
 * `check:visual`, to compile a few kilobytes of JSX that never changes between
 * runs. The bundle the cards render from (`_ds_bundle.js`) is already built
 * ahead of time by esbuild; the card bodies are the only JSX in the repo that
 * was still compiled at page load.
 *
 * Now the JSX lives beside the card as `<name>.card.jsx` — the SOURCE, edited by
 * hand — and this tool compiles it to `<name>.card.js`, which the card loads with
 * a plain `<script src>`. The compiled file is GENERATED and COMMITTED, on the
 * same terms as `_ds_bundle.js`: the browser gates render from it, so a stale
 * copy is a gate measuring something no source file says. `--check` runs in
 * `npm run check` for exactly that reason. **Edit a .card.jsx, run
 * `npm run cards`, commit both.**
 *
 * The transform is the CLASSIC one (`React.createElement`, `React.Fragment`),
 * not `jsx: "automatic"`: the cards get React as a UMD global from
 * `preview/_vendor/`, and there is no `react/jsx-runtime` to import. This is the
 * same reason `lw-bundle.mjs` uses the classic transform, and the same trap it
 * documents — an automatic-runtime card throws `jsx is not a function` and
 * renders blank, which axe scores as clean.
 *
 * Migration is built in rather than being a one-off script: in write mode, a
 * card that still carries an inline `<script type="text/babel">` block has it
 * extracted to the .jsx (several blocks concatenate in order), the block replaced
 * in place by the `<script src>`, and the babel.min.js tag removed. A
 * design-project re-pull would bring the inline form back; in check mode that
 * is a failure naming the card, not a silent return to load-time compilation.
 */
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";
import { generated } from "./_generated.mjs";
import { report } from "./_report.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const COMPONENTS = join(ROOT, "components");
const check = process.argv.includes("--check");

const BABEL_BLOCK = /[ \t]*<script\b[^>]*type\s*=\s*["']text\/babel["'][^>]*>([\s\S]*?)<\/script>[ \t]*\r?\n?/gi;
const BABEL_TAG = /[ \t]*<script\b[^>]*\bsrc\s*=\s*["'][^"']*babel(?:\.min)?\.js["'][^>]*>\s*<\/script>[ \t]*\r?\n?/gi;

/** The one esbuild call, shared by the compiler and by the header's promise. */
async function compile(jsx, sourcefile) {
  const { code } = await esbuild.transform(jsx, {
    loader: "jsx",
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    sourcefile,
    // A generated file must say so before anyone edits it by hand.
    banner: `/* GENERATED by tools/lw-cards.mjs from ${basename(sourcefile)} — edit the .jsx, run \`npm run cards\`. */`,
  });
  return code;
}

function walk(dir, out = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (e.name.endsWith(".card.html")) out.push(p);
  }
  return out;
}

const cards = walk(COMPONENTS).sort();
const problems = [];
const files = new Map();
let compiled = 0;
let migrated = 0;

for (const html of cards) {
  const rel = relative(ROOT, html);
  const stem = basename(html, ".card.html");
  const jsxPath = join(dirname(html), stem + ".card.jsx");
  const jsPath = join(dirname(html), stem + ".card.js");
  let src = readFileSync(html, "utf8");

  const inline = [...src.matchAll(BABEL_BLOCK)].map((m) => m[1]);
  if (inline.length) {
    if (check) {
      problems.push(`${rel} still carries ${inline.length} inline <script type="text/babel"> block(s) — run \`npm run cards\` to extract it`);
      continue;
    }
    // Migrate: the JSX becomes source, the block becomes a <script src>.
    const body = inline.map((b) => b.replace(/^\r?\n/, "").replace(/\s+$/, "")).join("\n\n") + "\n";
    if (existsSync(jsxPath)) {
      problems.push(`${rel} has an inline block AND a ${stem}.card.jsx — two sources; delete one`);
      continue;
    }
    writeFileSync(jsxPath, body);
    let first = true;
    src = src.replace(BABEL_BLOCK, (m) => {
      const indent = m.match(/^[ \t]*/)[0];
      const out = first ? `${indent}<script src="./${stem}.card.js"></script>\n` : "";
      first = false;
      return out;
    });
    src = src.replace(BABEL_TAG, "");
    writeFileSync(html, src);
    migrated++;
  }

  if (!existsSync(jsxPath)) continue; // a card with no React (ground.card.html) has nothing to compile

  if (BABEL_TAG.test(src)) problems.push(`${rel} still loads babel.min.js — nothing on the page compiles JSX any more`);
  BABEL_TAG.lastIndex = 0;
  if (!src.includes(`<script src="./${stem}.card.js"></script>`)) {
    problems.push(`${rel} does not load ./${stem}.card.js — the .card.jsx beside it is compiled to that file`);
  }

  const jsx = readFileSync(jsxPath, "utf8");
  try {
    files.set(jsPath, await compile(jsx, relative(ROOT, jsxPath)));
    compiled++;
  } catch (e) {
    problems.push(`${relative(ROOT, jsxPath)} does not compile: ${e.message.split("\n")[0]}`);
  }
}

if (files.size) {
  const stale = await generated({
    name: "lw-cards", files, check,
    hint: "run `npm run cards` and commit the result",
  });
  if (stale) process.exit(1);
}

process.exit(report("lw-cards", {
  problems,
  checked: compiled,
  minChecked: 20, // 27 today; a walk that finds a handful has lost the directory, not the cards
  summary: check
    ? `✓ lw-cards: ${compiled} .card.js current (${cards.length} cards, none inline)`
    : `lw-cards: ${compiled} compiled${migrated ? `, ${migrated} migrated from inline <script type="text/babel">` : ""}`,
}));
