#!/usr/bin/env node
/**
 * Emit the token core as a self-contained block for consumers that cannot import.
 *
 *   node tools/lw-inline.mjs                    # tokens only, to stdout
 *   node tools/lw-inline.mjs --fonts            # + @font-face with the woff2 inlined
 *   node tools/lw-inline.mjs --logo=lockup-ondark   # + a --lw-logo data URI
 *   node tools/lw-inline.mjs --out page.css     # write instead of printing
 *
 * ## Why this exists
 *
 * `tokens.css` opens with "Do not copy this file into an app; depend on the package",
 * and that is right for every consumer that has a bundler. It is unactionable for the
 * one that does not.
 *
 * A single-file HTML artifact — a report emailed to a customer, a briefing published
 * behind a password, a takeaway deck — has no npm, no build step, and no second
 * request: everything it renders with must already be inside the one file. Told to
 * depend on a package it cannot install, the author does the only thing left and
 * retypes the values. That is not a hypothetical: the SOP-mastery report shipped with
 * roughly thirty hand-transcribed HSL triples and four media queries at breakpoints
 * this package does not declare, and nothing in it could ever have reported drift.
 *
 * This package has already conceded this category once. `email.css` exists because
 * "an email is not a web page, and pretending otherwise is how a design system starts
 * shipping rules that silently do nothing". A single-file artifact is the same shape
 * of problem one step further out — not a different renderer, but a different *supply
 * chain* — and it deserves the same answer: a supported path, not a prohibition that
 * gets ignored.
 *
 * ## What it guarantees
 *
 * The output carries a provenance banner with the package version and the source
 * digest. That is the whole point: a vendored copy that says where it came from can
 * be diffed against a later release, and `lw-doctor` can be taught to read it. A
 * hand-typed one cannot be checked by anything, ever.
 *
 * It deliberately emits ONLY the token core — never the component layers. A static
 * artifact writes its own components; what it must not do is invent its own colour,
 * radius, spacing or breakpoint values.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));

// The output is ~80 KB and the first thing anyone does with it is `| head`. Node
// turns the resulting EPIPE into an unhandled 'error' event and a stack trace, which
// reads as a broken tool rather than a closed pipe.
process.stdout.on("error", (e) => { if (e.code === "EPIPE") process.exit(0); throw e; });

const args = process.argv.slice(2);
const has = (f) => args.includes(f);
const val = (f) => {
  const hit = args.find((a) => a.startsWith(`${f}=`));
  return hit ? hit.slice(f.length + 1) : null;
};

const tokens = readFileSync(join(ROOT, "tokens.css"), "utf8");
const digest = createHash("sha256").update(tokens).digest("hex").slice(0, 12);

const out = [];
out.push(
  "/* =============================================================================",
  `   @leanwise/design v${pkg.version} — token core, vendored inline.`,
  `   tokens.css sha256:${digest}`,
  "",
  "   GENERATED by `npx lw-inline`. Do not edit these values by hand: the digest",
  "   above is the only thing that can tell a later reader whether this block still",
  "   matches the package. Re-run the generator instead, and diff.",
  "",
  "   Vendored because this artifact cannot import — a single file with no build",
  "   step and no second request. Every OTHER kind of consumer must depend on the",
  "   package: see README §Install.",
  "   ============================================================================= */",
  "",
);

// Emit the token core verbatim. Stripping its comments was considered and rejected:
// the comments are where the reasoning lives (why --lw-logo-cyan may not be consumed
// by a UI rule, why brand-500 is darker than the mark's cyan), and a vendored copy
// that keeps the values while dropping the reasons is how the values get "improved".
out.push(tokens.trimEnd(), "");

if (has("--fonts")) {
  const FONTS = [
    { file: "geist-latin-4.woff2", family: "Geist", weight: "400 700" },
    { file: "geist-latin-ext-3.woff2", family: "Geist", weight: "400 700" },
    { file: "geist-mono-latin-10.woff2", family: "Geist Mono", weight: "400 600" },
  ];
  out.push("/* ---- fonts, inlined as data URIs ---------------------------------------- */");
  for (const f of FONTS) {
    let b64;
    try {
      b64 = readFileSync(join(ROOT, "fonts", f.file)).toString("base64");
    } catch {
      console.error(`✗ fonts/${f.file} not found — cannot inline fonts`);
      process.exit(1);
    }
    out.push(
      `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weight};`,
      `  font-display:swap;src:url(data:font/woff2;base64,${b64}) format('woff2');}`,
    );
  }
  out.push("");
}

const logo = val("--logo");
if (logo) {
  const file = `logo-${logo}.svg`;
  let svg;
  try {
    svg = readFileSync(join(ROOT, "assets", file));
  } catch {
    console.error(
      `✗ assets/${file} not found. Use one of: mark, mark-mono, lockup, lockup-ondark, favicon.`,
    );
    process.exit(1);
  }
  if (logo === "mark-mono") {
    // currentColor cannot resolve inside a data: URI — the SVG would paint black.
    // Refusing beats emitting something that renders wrong on the ground it was
    // picked for; README §Logo says this variant must be inlined or used as a mask.
    console.error(
      "✗ logo-mark-mono.svg is currentColor by design and CANNOT be a data URI —\n" +
        "  currentColor resolves against the SVG's own root there, so it paints black.\n" +
        "  Inline the markup, or use it as a CSS mask and set the colour on the box.",
    );
    process.exit(1);
  }
  out.push(
    "/* ---- logo, inlined ------------------------------------------------------ */",
    `/* assets/${file}. Artwork — never recolour it, never run it through a filter. */`,
    `:root{--lw-logo:url("data:image/svg+xml;base64,${svg.toString("base64")}")}`,
    "",
  );
}

const text = out.join("\n");
const dest = val("--out");
if (dest) {
  writeFileSync(dest, text);
  console.error(`wrote ${dest}  ${(Buffer.byteLength(text) / 1024).toFixed(1)} KB`);
} else {
  process.stdout.write(text);
}
