/* GENERATED by tools/lw-cards.mjs from BottomNav.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { BottomNav } = LW;
const items = [
  { value: "ask", label: "Ask", icon: "spark" },
  { value: "sources", label: "Sources", icon: "database" },
  { value: "activity", label: "Activity", icon: "bell", badge: 3 },
  { value: "you", label: "You", icon: "user" }
];
function Demo() {
  const [v, setV] = React.useState("ask");
  return /* @__PURE__ */ React.createElement("div", { style: { border: "1px solid var(--lw-line)", borderRadius: 12, overflow: "hidden", background: "var(--lw-bg)" } }, /* @__PURE__ */ React.createElement("div", { style: { height: 200, display: "grid", placeItems: "center", fontSize: "var(--lw-text-sm)", color: "var(--lw-fg-subtle)" } }, items.find((i) => i.value === v).label), /* @__PURE__ */ React.createElement(BottomNav, { items, value: v, onChange: setV }));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
