/* GENERATED by tools/lw-cards.mjs from CommandPalette.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { CommandPalette, Button, Cluster } = LW;
const commands = [
  { id: 1, group: "Sources", label: "Open database", icon: "database", kbd: "\u2318O", keywords: ["db", "connect"] },
  { id: 2, group: "Sources", label: "Re-index contracts/2024", icon: "retry" },
  { id: 3, group: "Sources", label: "Upload documents", icon: "upload" },
  { id: 4, group: "Workspace", label: "Invite a teammate", icon: "users", kbd: "\u2318I" },
  { id: 5, group: "Workspace", label: "Switch theme", icon: "moon" },
  { id: 6, group: "Workspace", label: "Open settings", icon: "settings", kbd: "\u2318," },
  { id: 7, group: "Danger", label: "Delete this workspace", icon: "trash" }
];
function Demo() {
  const [open, setOpen] = React.useState(false);
  React.useEffect(() => {
    const h = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setOpen((o) => !o);
      }
    };
    window.addEventListener("keydown", h);
    return () => window.removeEventListener("keydown", h);
  }, []);
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Cluster, null, /* @__PURE__ */ React.createElement(Button, { onClick: () => setOpen(true) }, "Open palette"), /* @__PURE__ */ React.createElement("span", { className: "lw-menu-kbd" }, "or \u2318K")), /* @__PURE__ */ React.createElement(CommandPalette, { open, onClose: () => setOpen(false), commands, onRun: () => {
  } }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(Demo, null));
