/* GENERATED by tools/lw-cards.mjs from CommandPalette.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Icon } = LW;
const commands = [
  { id: 1, group: "Sources", label: "Open database", icon: "database", kbd: "\u2318O" },
  { id: 2, group: "Sources", label: "Re-index contracts/2024", icon: "retry" },
  { id: 3, group: "Sources", label: "Upload documents", icon: "upload" },
  { id: 4, group: "Workspace", label: "Invite a teammate", icon: "users", kbd: "\u2318I" },
  { id: 5, group: "Workspace", label: "Switch theme", icon: "moon" },
  { id: 6, group: "Workspace", label: "Open settings", icon: "settings", kbd: "\u2318," },
  { id: 7, group: "Danger", label: "Delete this workspace", icon: "trash" }
];
function Palette({ query, active }) {
  const uid = React.useId();
  let lastGroup = null;
  return /* @__PURE__ */ React.createElement("div", { className: "lw-cmdk" }, /* @__PURE__ */ React.createElement("div", { className: "lw-cmdk-input" }, /* @__PURE__ */ React.createElement(Icon, { name: "search", size: 17 }), /* @__PURE__ */ React.createElement(
    "input",
    {
      type: "text",
      role: "combobox",
      "aria-expanded": "true",
      "aria-controls": uid,
      "aria-activedescendant": uid + "-" + active,
      "aria-label": "Command palette",
      placeholder: "Type a command\u2026",
      defaultValue: query
    }
  )), /* @__PURE__ */ React.createElement("ul", { className: "lw-cmdk-list lw-menu", id: uid, role: "listbox", "aria-label": "Command palette" }, commands.map((c, i) => {
    const head = c.group !== lastGroup ? lastGroup = c.group : null;
    return /* @__PURE__ */ React.createElement(React.Fragment, { key: c.id }, head && /* @__PURE__ */ React.createElement("li", { className: "lw-menu-label", role: "presentation" }, head), /* @__PURE__ */ React.createElement(
      "li",
      {
        id: uid + "-" + i,
        role: "option",
        "aria-selected": i === active,
        className: "lw-menu-item",
        "data-active": i === active ? "true" : void 0,
        style: i === active ? { background: "var(--lw-bg-subtle)" } : void 0
      },
      /* @__PURE__ */ React.createElement("span", { className: "lw-menu-lead" }, /* @__PURE__ */ React.createElement(Icon, { name: c.icon, size: 15 })),
      /* @__PURE__ */ React.createElement("span", { className: "lw-menu-text" }, c.label),
      c.kbd && /* @__PURE__ */ React.createElement("span", { className: "lw-menu-kbd" }, c.kbd)
    ));
  })), /* @__PURE__ */ React.createElement("div", { className: "lw-cmdk-foot" }, /* @__PURE__ */ React.createElement("span", null, "\u2191\u2193 to move"), /* @__PURE__ */ React.createElement("span", null, "\u23CE to run"), /* @__PURE__ */ React.createElement("span", null, "esc to close")));
}
function Demo() {
  return /* @__PURE__ */ React.createElement("div", { className: "stage" }, /* @__PURE__ */ React.createElement("div", { className: "lw-backdrop" }), /* @__PURE__ */ React.createElement(Palette, { query: "", active: 1 }));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
