/* GENERATED by tools/lw-cards.mjs from TopBarMobile.card.jsx — edit the .jsx, run `npm run cards`. */
const { TopBar, Icon } = window.LeanWiseDesign_f2d907;
const LINKS = [
  { href: "#product", label: "Product" },
  { href: "#customers", label: "Customers" },
  { href: "#pricing", label: "Pricing" },
  { href: "#company", label: "Company", current: true }
];
function Frame({ open, id }) {
  const panelId = id + "-panel";
  return /* @__PURE__ */ React.createElement("div", { className: "mobileframe" + (open ? " open" : "") }, /* @__PURE__ */ React.createElement(TopBar, { brand: "LeanWise AI", logo: true, brandHref: "#home", links: LINKS }, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      className: "lw-topbar-toggle lw-icon-btn lw-hit",
      "aria-expanded": open,
      "aria-controls": panelId,
      "aria-label": open ? "Close menu" : "Menu"
    },
    /* @__PURE__ */ React.createElement(Icon, { name: open ? "close" : "menu", size: 20 })
  ), /* @__PURE__ */ React.createElement("div", { id: panelId, className: "lw-topbar-panel", hidden: !open }, /* @__PURE__ */ React.createElement("nav", { "aria-label": "Primary, narrow" }, LINKS.map((l) => /* @__PURE__ */ React.createElement("a", { key: l.href, href: l.href, "aria-current": l.current ? "page" : void 0 }, l.label))))), /* @__PURE__ */ React.createElement("div", { className: "body" }, "Page content stays visible and interactive \u2014 the panel is a disclosure, not a modal."));
}
function Pane({ side }) {
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "closed"), /* @__PURE__ */ React.createElement(Frame, { open: false, id: side + "-closed" }), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above", style: { marginTop: 14 } }, "open"), /* @__PURE__ */ React.createElement(Frame, { open: true, id: side + "-open" }));
}
for (const id of ["light", "dark"]) {
  ReactDOM.createRoot(document.getElementById(id)).render(/* @__PURE__ */ React.createElement(Pane, { side: id }));
}
