/* GENERATED by tools/lw-cards.mjs from Combobox.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Combobox, Field, Stack } = LW;
const sources = [
  { value: "contracts", label: "contracts/2024", meta: "41,208" },
  { value: "handbook", label: "policies/handbook", meta: "3,860" },
  { value: "tickets", label: "support/tickets", meta: "12,004" },
  { value: "specs", label: "product/specs", meta: "8,412" },
  { value: "legal", label: "legal/archive", meta: "0", disabled: true }
];
function Demo() {
  const [one, setOne] = React.useState("handbook");
  const [many, setMany] = React.useState(["contracts", "tickets"]);
  return /* @__PURE__ */ React.createElement(Stack, { gap: 16 }, /* @__PURE__ */ React.createElement(Field, { label: "Source", help: "Type to filter. Arrows move, Enter picks." }, /* @__PURE__ */ React.createElement(Combobox, { options: sources, value: one, onChange: setOne, placeholder: "Choose a source", label: "Source" })), /* @__PURE__ */ React.createElement(Field, { label: "Include in this query", help: "Backspace removes the last token; each token has its own control." }, /* @__PURE__ */ React.createElement(Combobox, { multiple: true, options: sources, value: many, onChange: setMany, placeholder: "Add sources", label: "Include in this query" })), /* @__PURE__ */ React.createElement(Field, { label: "Restricted", error: "Pick a source you have access to." }, /* @__PURE__ */ React.createElement(Combobox, { options: sources, invalid: true, placeholder: "No access", label: "Restricted" })));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
