/* GENERATED by tools/lw-cards.mjs from DatePicker.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { FileUpload, Field, Stack, Icon } = LW;
const DOW = ["M", "T", "W", "T", "F", "S", "S"];
const LEAD = [29, 30], DAYS = 31, TRAIL = 42 - LEAD.length - DAYS;
function CalDay({ n, outside, today, selected, inRange, edge, off }) {
  return /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      role: "gridcell",
      className: "lw-cal-day",
      tabIndex: n === 24 && !outside ? 0 : -1,
      "aria-selected": selected || void 0,
      "aria-label": outside ? String(n) : n + " July 2026",
      "aria-disabled": off || void 0,
      "data-outside": outside ? "true" : void 0,
      "data-today": today ? "true" : void 0,
      "data-in-range": inRange ? "true" : void 0,
      "data-edge": edge
    },
    n
  );
}
function Cal({ range }) {
  const cells = [
    ...LEAD.map((n) => ({ n, outside: true })),
    ...Array.from({ length: DAYS }, (_, i) => {
      const n = i + 1;
      return {
        n,
        today: n === 17,
        selected: range ? n === 20 || n === 29 : n === 24,
        inRange: range && n > 20 && n < 29,
        edge: range ? n === 20 ? "start" : n === 29 ? "end" : void 0 : void 0,
        off: n > 29
      };
    }),
    ...Array.from({ length: TRAIL }, (_, i) => ({ n: i + 1, outside: true }))
  ];
  const weeks = Array.from({ length: 6 }, (_, w) => cells.slice(w * 7, w * 7 + 7));
  return /* @__PURE__ */ React.createElement("div", { className: "lw-cal" }, /* @__PURE__ */ React.createElement("div", { className: "lw-cal-head" }, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Previous month" }, /* @__PURE__ */ React.createElement(Icon, { name: "chevron-left", size: 16 })), /* @__PURE__ */ React.createElement("div", { className: "lw-cal-month", "aria-live": "polite" }, "July 2026"), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-icon-btn", "aria-label": "Next month" }, /* @__PURE__ */ React.createElement(Icon, { name: "chevron-right", size: 16 }))), /* @__PURE__ */ React.createElement("div", { className: "lw-cal-grid", role: "grid", "aria-label": range ? "Reporting period" : "Effective date" }, /* @__PURE__ */ React.createElement("div", { role: "row", className: "lw-cal-dow-row" }, DOW.map((d, i) => /* @__PURE__ */ React.createElement("div", { key: i, role: "columnheader", className: "lw-cal-dow" }, d))), /* @__PURE__ */ React.createElement("div", { role: "rowgroup", className: "lw-cal-weeks" }, weeks.map((week, w) => /* @__PURE__ */ React.createElement("div", { key: w, role: "row", className: "lw-cal-week" }, week.map((c, i) => /* @__PURE__ */ React.createElement(CalDay, { key: i, ...c })))))));
}
const DateField = ({ text, placeholder }) => /* @__PURE__ */ React.createElement(
  "button",
  {
    type: "button",
    className: "lw-input lw-datefield",
    "data-placeholder": text ? void 0 : "true",
    "aria-label": placeholder
  },
  /* @__PURE__ */ React.createElement(Icon, { name: "calendar", size: 15, className: "lw-datefield-ic" }),
  /* @__PURE__ */ React.createElement("span", { className: "lw-datefield-text" }, text || placeholder)
);
function Steps({ current }) {
  const steps = [{ label: "Connect" }, { label: "Map fields" }, { label: "Review" }, { label: "Publish" }];
  return /* @__PURE__ */ React.createElement("div", { className: "lw-stepper", role: "group", "aria-label": "Progress" }, steps.map((s, i) => {
    const state = i < current ? "done" : i === current ? "current" : "upcoming";
    return /* @__PURE__ */ React.createElement(
      "div",
      {
        key: i,
        className: "lw-stepper-step",
        "data-state": state,
        "aria-current": state === "current" ? "step" : void 0
      },
      /* @__PURE__ */ React.createElement("span", { className: "lw-stepper-marker", "aria-hidden": "true" }, state === "done" ? /* @__PURE__ */ React.createElement(Icon, { name: "checkmark", size: 14 }) : i + 1),
      /* @__PURE__ */ React.createElement("span", { className: "lw-stepper-label" }, s.label, /* @__PURE__ */ React.createElement("span", { className: "lw-sr-only" }, " \u2014 " + (state === "done" ? "completed" : state === "current" ? "current step" : "not started")))
    );
  }));
}
function Demo() {
  const [files, setFiles] = React.useState([
    { id: 1, name: "contracts-2024-q1.pdf", size: 2411724, state: "done" },
    { id: 2, name: "handbook-v9.docx", size: 840112, state: "uploading", progress: 62 },
    { id: 3, name: "scan-0042.tiff", size: 51203344, state: "error", error: "Unsupported format \u2014 PDF, DOCX or TXT" }
  ]);
  return /* @__PURE__ */ React.createElement(Stack, { gap: 16 }, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "stepper \u2014 the marker carries the state"), /* @__PURE__ */ React.createElement(Steps, { current: 2 }), /* @__PURE__ */ React.createElement(Field, { label: "Effective date" }, /* @__PURE__ */ React.createElement(DateField, { text: "24 July 2026", placeholder: "Pick a date" })), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "the panel, open \u2014 every cell state at once"), /* @__PURE__ */ React.createElement("div", { className: "lw-cal-wrap" }, /* @__PURE__ */ React.createElement(Cal, null)), /* @__PURE__ */ React.createElement(Field, { label: "Reporting period", help: "Presets first \u2014 the grid is for the tenth case." }, /* @__PURE__ */ React.createElement(DateField, { text: "20 \u2013 29 July 2026", placeholder: "Pick a range" })), /* @__PURE__ */ React.createElement("div", { className: "lw-cal-wrap" }, /* @__PURE__ */ React.createElement("div", { className: "lw-cal-presets" }, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-cal-preset" }, "Last 7 days"), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-cal-preset", "aria-current": "true" }, "Last 30 days"), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-cal-preset" }, "This quarter"), /* @__PURE__ */ React.createElement("button", { type: "button", className: "lw-cal-preset" }, "Year to date")), /* @__PURE__ */ React.createElement(Cal, { range: true })), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "upload"), /* @__PURE__ */ React.createElement(
    FileUpload,
    {
      multiple: true,
      accept: ".pdf,.docx,.txt",
      maxSize: 20 * 1024 * 1024,
      files,
      onFiles: (fs) => setFiles((x) => [...x, ...fs.map((f, i) => ({ id: Date.now() + i, name: f.name, size: f.size, state: "queued" }))]),
      onRemove: (f) => setFiles((x) => x.filter((y) => y.id !== f.id))
    }
  ));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
