/* GENERATED by tools/lw-cards.mjs from DatePicker.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { DatePicker, FileUpload, Stepper, Field, Stack } = LW;
function Demo() {
  const [d, setD] = React.useState(new Date(2026, 6, 24));
  const [r, setR] = React.useState({ start: new Date(2026, 6, 20), end: new Date(2026, 6, 29) });
  const [files, setFiles] = React.useState([
    { id: 1, name: "contracts-2024-q1.pdf", size: 2411724, state: "done" },
    { id: 2, name: "handbook-v9.docx", size: 840112, state: "uploading", progress: 62 },
    { id: 3, name: "scan-0042.tiff", size: 51203344, state: "error", error: "Unsupported format \u2014 PDF, DOCX or TXT" }
  ]);
  return /* @__PURE__ */ React.createElement(Stack, { gap: 16 }, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "stepper \u2014 the marker carries the state"), /* @__PURE__ */ React.createElement(Stepper, { current: 2, steps: [{ label: "Connect" }, { label: "Map fields" }, { label: "Review" }, { label: "Publish" }] }), /* @__PURE__ */ React.createElement(Field, { label: "Effective date" }, /* @__PURE__ */ React.createElement(DatePicker, { value: d, onChange: setD, label: "Effective date" })), /* @__PURE__ */ React.createElement(Field, { label: "Reporting period", help: "Presets first \u2014 the grid is for the tenth case." }, /* @__PURE__ */ React.createElement(DatePicker, { range: true, value: r, onChange: setR, label: "Reporting period" })), /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "upload"), /* @__PURE__ */ React.createElement(
    FileUpload,
    {
      multiple: true,
      accept: ".pdf,.docx,.txt",
      maxSize: 20 * 1024 * 1024,
      files,
      onFiles: (fs) => setFiles((x) => [...x, ...fs.map((f, i) => ({ id: Date.now() + i, name: f.name, size: f.size, state: "queued" }))]),
      onRemove: (f) => setFiles((x) => x.filter((y) => y.id !== f.id))
    }
  ));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
