/* GENERATED by tools/lw-cards.mjs from RichText.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { Field, Icon } = LW;
const TOOLS = [
  { id: "bold", label: "Bold", glyph: "B" },
  { id: "italic", label: "Italic", glyph: "I" },
  { sep: true },
  { id: "h2", label: "Heading", glyph: "H" },
  { id: "ul", icon: "list", label: "Bulleted list" },
  { id: "ol", icon: "sort-asc", label: "Numbered list" },
  { id: "quote", icon: "quote", label: "Quote" },
  { id: "code", icon: "code", label: "Code" },
  { sep: true },
  { id: "link", icon: "link", label: "Link" },
  { id: "clear", icon: "undo", label: "Clear formatting" }
];
function Bar({ active = {}, readOnly }) {
  return /* @__PURE__ */ React.createElement("div", { className: "lw-editor-bar", role: "group", "aria-label": "Formatting" }, TOOLS.map((t, i) => t.sep ? /* @__PURE__ */ React.createElement("span", { key: "s" + i, className: "sep", "aria-hidden": "true" }) : /* @__PURE__ */ React.createElement(
    "button",
    {
      key: t.id,
      type: "button",
      className: "lw-icon-btn",
      "aria-label": t.label,
      title: t.label,
      "aria-pressed": !!active[t.id],
      disabled: readOnly
    },
    t.glyph ? /* @__PURE__ */ React.createElement("span", { className: "lw-editor-glyph", "data-glyph": t.id }, t.glyph) : /* @__PURE__ */ React.createElement(Icon, { name: t.icon, size: 15 })
  )));
}
function Editor({ readOnly, count, children }) {
  return /* @__PURE__ */ React.createElement("div", { className: "lw-editor" }, /* @__PURE__ */ React.createElement(Bar, { active: readOnly ? {} : { bold: true }, readOnly }), /* @__PURE__ */ React.createElement(
    "div",
    {
      className: "lw-prose lw-editor-body",
      role: "textbox",
      "aria-multiline": "true",
      "aria-label": readOnly ? "Locked summary" : "Summary",
      "aria-readonly": readOnly || void 0
    },
    children
  ), count && /* @__PURE__ */ React.createElement("div", { className: "lw-editor-foot" }, /* @__PURE__ */ React.createElement("span", { className: "lw-spacer" }), /* @__PURE__ */ React.createElement("span", { className: "lw-editor-count", "aria-live": "polite" }, count)));
}
function Demo() {
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Field, { label: "Summary", help: "Bold, italic, headings, lists, quote, code and links." }, /* @__PURE__ */ React.createElement(Editor, { count: "218 / 600" }, /* @__PURE__ */ React.createElement("h2", null, "Termination clause"), /* @__PURE__ */ React.createElement("p", null, "Either party may terminate for convenience on ", /* @__PURE__ */ React.createElement("strong", null, "60 days'"), " written notice."), /* @__PURE__ */ React.createElement("ul", null, /* @__PURE__ */ React.createElement("li", null, "Rises to 90 days after the second renewal"), /* @__PURE__ */ React.createElement("li", null, "Notice must be in writing")))), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "read-only \u2014 same chrome, no editing"), /* @__PURE__ */ React.createElement(Editor, { readOnly: true }, /* @__PURE__ */ React.createElement("p", null, "Locked while the source re-indexes."))), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "over the limit"), /* @__PURE__ */ React.createElement("div", { className: "lw-editor" }, /* @__PURE__ */ React.createElement(Bar, null), /* @__PURE__ */ React.createElement("div", { className: "lw-prose lw-editor-body", role: "textbox", "aria-multiline": "true", "aria-label": "Long summary" }, /* @__PURE__ */ React.createElement("p", null, "A summary that has run past what the field will accept.")), /* @__PURE__ */ React.createElement("div", { className: "lw-editor-foot" }, /* @__PURE__ */ React.createElement("span", { className: "lw-spacer" }), /* @__PURE__ */ React.createElement("span", { className: "lw-editor-count", "data-over": "true", "aria-live": "polite" }, "641 / 600")))));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
