/* GENERATED by tools/lw-cards.mjs from RichText.card.jsx — edit the .jsx, run `npm run cards`. */
const LW = window.LeanWiseDesign_f2d907;
const { RichText, Field } = LW;
function Demo() {
  const [html, setHtml] = React.useState("<h2>Termination clause</h2><p>Either party may terminate for convenience on <strong>60 days'</strong> written notice.</p><ul><li>Rises to 90 days after the second renewal</li><li>Notice must be in writing</li></ul>");
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Field, { label: "Summary", help: "Bold, italic, headings, lists, quote, code and links." }, /* @__PURE__ */ React.createElement(RichText, { value: html, onChange: setHtml, maxLength: 600, label: "Summary" })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "lbl-eyebrow lbl-above" }, "read-only \u2014 same chrome, no editing"), /* @__PURE__ */ React.createElement(RichText, { value: "<p>Locked while the source re-indexes.</p>", readOnly: true, label: "Locked summary" })));
}
ReactDOM.createRoot(document.getElementById("light")).render(/* @__PURE__ */ React.createElement(Demo, null));
ReactDOM.createRoot(document.getElementById("dark")).render(/* @__PURE__ */ React.createElement(Demo, null));
